
package jws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jws.service.ObjectFactory;
import jws.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JwsIService", targetNamespace = "http://service.jws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JwsIService {


    /**
     * 
     * @param secondNum
     * @param firstNum
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "multiplyResult", targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://service.jws/", className = "jws.service.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://service.jws/", className = "jws.service.MultiplyResponse")
    @Action(input = "http://service.jws/JwsIService/multiplyRequest", output = "http://service.jws/JwsIService/multiplyResponse")
    public int multiply(
        @WebParam(name = "firstNum", targetNamespace = "")
        int firstNum,
        @WebParam(name = "secondNum", targetNamespace = "")
        int secondNum);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns jws.service.User
     */
    @WebMethod
    @WebResult(name = "loginUserInfo", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.jws/", className = "jws.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.jws/", className = "jws.service.LoginResponse")
    @Action(input = "http://service.jws/JwsIService/loginRequest", output = "http://service.jws/JwsIService/loginResponse")
    public User login(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param secondNum
     * @param firstNum
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "sumResult", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://service.jws/", className = "jws.service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://service.jws/", className = "jws.service.SumResponse")
    @Action(input = "http://service.jws/JwsIService/sumRequest", output = "http://service.jws/JwsIService/sumResponse")
    public int sum(
        @WebParam(name = "firstNum", targetNamespace = "")
        int firstNum,
        @WebParam(name = "secondNum", targetNamespace = "")
        int secondNum);

}
